GET_FILENAME_COMPONENT(SELF_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
INCLUDE(${SELF_DIR}/ragolibcpp-targets.cmake)
GET_FILENAME_COMPONENT(ragolibcpp_INCLUDE_DIRS "${SELF_DIR}/../../include/ragolibcpp" ABSOLUTE)
